# I use C as a language setting because OS X on Travis doesn't support C++.
# This setting is actually irrelevant because C++ compilers will be installed
# and specified manually.
language: c
os:
    - linux
env:
    matrix:
        - LLVM_VERSION="-3.4" CMAKE_OPTS="-DCMAKE_CXX_FLAGS=-I/usr/lib/llvm-3.4/lib/clang/3.4.1/include -DDACHS_LLVM_CONFIG=/usr/bin/llvm-config-3.4 -DDACHS_USE_LLVM_SHARED_LIB=1"
        - LLVM_VERSION="-3.5" CMAKE_OPTS="-DDACHS_LLVM_CONFIG=/usr/bin/llvm-config-3.5 -DDACHS_CXX_COMPILER=/usr/bin/clang++-3.5 -DDACHS_USE_LLVM_SHARED_LIB=1"
        - LLVM_VERSION="-3.6" CMAKE_OPTS="-DDACHS_LLVM_CONFIG=/usr/bin/llvm-config-3.6 -DDACHS_CXX_COMPILER=/usr/bin/clang++-3.6 -DDACHS_USE_LLVM_SHARED_LIB=1"
        - LLVM_VERSION="-3.7" CMAKE_OPTS="-DDACHS_LLVM_CONFIG=/usr/bin/llvm-config-3.7 -DDACHS_CXX_COMPILER=/usr/bin/clang++-3.7 -DDACHS_USE_LLVM_SHARED_LIB=1"
matrix:
    include:
        - os: osx
          env: LLVM_VERSION="" CMAKE_OPTS="-DDACHS_LLVM_CONFIG=/usr/local/bin/llvm-config -DDACHS_CXX_COMPILER=/usr/local/bin/clang++"
    allow_failures:
        - env: LLVM_VERSION="-3.6" CMAKE_OPTS="-DDACHS_LLVM_CONFIG=/usr/bin/llvm-config-3.6 -DDACHS_CXX_COMPILER=/usr/bin/clang++-3.6 -DDACHS_USE_LLVM_SHARED_LIB=1"
        - env: LLVM_VERSION="-3.7" CMAKE_OPTS="-DDACHS_LLVM_CONFIG=/usr/bin/llvm-config-3.7 -DDACHS_CXX_COMPILER=/usr/bin/clang++-3.7 -DDACHS_USE_LLVM_SHARED_LIB=1"
        - env: LLVM_VERSION="" CMAKE_OPTS="-DDACHS_LLVM_CONFIG=/usr/local/bin/llvm-config -DDACHS_CXX_COMPILER=/usr/local/bin/clang++"
script: |
    uname -a
    /usr/bin/clang++${LLVM_VERSION} -v
    mkdir -p build && cd build
    cmake --version
    cmake .. $CMAKE_OPTS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.
    make VERBOSE=1 install && (make test || (cat Testing/Temporary/LastTestsFailed.log && ../test/output_error.sh && false))
before_install: |
    case $TRAVIS_OS_NAME in
    linux)
        sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main' >> /etc/apt/sources.list"
        sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
        sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6-binaries main' >> /etc/apt/sources.list"
        sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
        sudo sh -c "echo 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main' >> /etc/apt/sources.list"
        wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
        sudo add-apt-repository --yes ppa:boost-latest/ppa
        sudo add-apt-repository --yes ppa:kalakris/cmake
        ;;
    osx)
        brew update
        ;;
    esac
install: |
    case $TRAVIS_OS_NAME in
    linux)
        sudo apt-get -qq update
        sudo apt-get -qq install g++-4.9 libboost1.55-all-dev cmake llvm${LLVM_VERSION}-dev clang${LLVM_VERSION}
        ;;
    osx)
        brew install llvm --with-clang
        ;;
    esac
git:
    submodules: false
