version: "{build}"
clone_depth: 1
clone_folder: c:\gopath\src\github.com\rhysd\Dachs
environment:
    GOPATH: c:\gopath
install:
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - go get golang.org/x/tools/cmd/goyacc
    - cd .\next\compiler
    - go get -v -t -d ./...
    - set PATH=%PATH%;%GOPATH%\bin
build: off
test_script:
    - goyacc -o syntax/grammar.go syntax/grammar.go.y
    - go test -v ./...
deploy: off
